"""
Database initialization and access layer.

SQLite via aiosqlite. Raw parameterized SQL only — no ORM.
All tables created with IF NOT EXISTS for idempotent init.
Both systems share one DB file with 'system' column for isolation.

Usage:
    from shared.db.models import init_db, get_db

    # At startup
    await init_db("/path/to/trading.db")

    # In modules
    async with get_db() as db:
        await db.execute("INSERT INTO trades ...", params)
"""

from __future__ import annotations

import aiosqlite

from shared.utils.logger import get_logger

logger = get_logger(__name__)

# ─── Module-level DB path (set by init_db) ───
_db_path: str | None = None


# ─── Table DDL ───

_TRADES_TABLE = """
CREATE TABLE IF NOT EXISTS trades (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    system          TEXT NOT NULL,
    date            TEXT NOT NULL,
    symbol          TEXT NOT NULL,
    sector          TEXT,
    direction       TEXT NOT NULL,
    status          TEXT NOT NULL DEFAULT 'planned',

    -- Plan (generated by system)
    entry_price     REAL NOT NULL,
    stop_loss       REAL NOT NULL,
    stop_loss_pct   REAL NOT NULL,
    target_1        REAL NOT NULL,
    target_2        REAL,
    rr_ratio        REAL NOT NULL,
    position_size   INTEGER NOT NULL,
    position_value  REAL NOT NULL,
    max_risk        REAL NOT NULL,
    confidence      TEXT NOT NULL,
    max_hold_days   INTEGER NOT NULL DEFAULT 3,

    -- Execution (filled when trade is taken/closed)
    actual_entry    REAL,
    entry_time      TEXT,
    actual_exit     REAL,
    exit_time       TEXT,
    exit_reason     TEXT,

    -- Result (computed on close)
    pnl             REAL,
    pnl_pct         REAL,
    hold_hours      REAL,

    -- Scores (what drove the pick)
    technical_score  INTEGER,
    macro_score      INTEGER,
    fundamental_score INTEGER,
    composite_score  REAL,
    reasons          TEXT,

    -- Timestamps
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
"""

_SIGNALS_TABLE = """
CREATE TABLE IF NOT EXISTS signals (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    system          TEXT NOT NULL,
    date            TEXT NOT NULL,
    signal_type     TEXT NOT NULL,
    symbol          TEXT,
    direction       TEXT,
    score           INTEGER,
    data            TEXT NOT NULL,
    source          TEXT NOT NULL,
    was_correct     INTEGER,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
"""

_DAILY_KPIS_TABLE = """
CREATE TABLE IF NOT EXISTS daily_kpis (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    system          TEXT NOT NULL,
    date            TEXT NOT NULL,
    trades_taken    INTEGER NOT NULL DEFAULT 0,
    wins            INTEGER NOT NULL DEFAULT 0,
    losses          INTEGER NOT NULL DEFAULT 0,
    no_trade        INTEGER NOT NULL DEFAULT 0,
    net_pnl         REAL NOT NULL DEFAULT 0,
    net_pnl_pct     REAL NOT NULL DEFAULT 0,
    win_rate        REAL,
    profit_factor   REAL,
    max_drawdown    REAL,
    data            TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),

    UNIQUE(system, date)
);
"""

_WEIGHT_HISTORY_TABLE = """
CREATE TABLE IF NOT EXISTS weight_history (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    system          TEXT NOT NULL,
    date            TEXT NOT NULL,
    technical_wt    REAL NOT NULL,
    macro_wt        REAL NOT NULL,
    fundamental_wt  REAL NOT NULL,
    trigger         TEXT NOT NULL,
    reason          TEXT,
    prev_technical  REAL,
    prev_macro      REAL,
    prev_fundamental REAL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
"""

_INGESTION_LOG_TABLE = """
CREATE TABLE IF NOT EXISTS ingestion_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    system          TEXT NOT NULL,
    timestamp       TEXT NOT NULL,
    provider        TEXT NOT NULL,
    module          TEXT NOT NULL,
    status          TEXT NOT NULL,
    latency_ms      INTEGER,
    data_points     INTEGER,
    error           TEXT,
    fallback_used   TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
"""

_ALERTS_SENT_TABLE = """
CREATE TABLE IF NOT EXISTS alerts_sent (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    system          TEXT NOT NULL,
    timestamp       TEXT NOT NULL,
    alert_type      TEXT NOT NULL,
    symbol          TEXT,
    content_hash    TEXT,
    telegram_msg_id TEXT,
    status          TEXT NOT NULL,
    error           TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
"""

# ─── Indexes ───

_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_trades_system_date ON trades(system, date);",
    "CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);",
    "CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);",
    "CREATE INDEX IF NOT EXISTS idx_signals_system_date ON signals(system, date);",
    "CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type);",
    "CREATE INDEX IF NOT EXISTS idx_ingestion_system_date ON ingestion_log(system, timestamp);",
    "CREATE INDEX IF NOT EXISTS idx_ingestion_status ON ingestion_log(status);",
]


async def init_db(db_path: str) -> None:
    """Initialize database — create all tables and indexes.

    Safe to call multiple times (IF NOT EXISTS).
    Must be called once at application startup.

    Args:
        db_path: Full path to SQLite database file.
    """
    global _db_path
    _db_path = db_path

    # Ensure db directory exists
    from pathlib import Path

    Path(db_path).parent.mkdir(parents=True, exist_ok=True)

    async with aiosqlite.connect(db_path) as db:
        # Enable WAL mode for better concurrent read performance
        await db.execute("PRAGMA journal_mode=WAL;")

        # Create tables
        await db.execute(_TRADES_TABLE)
        await db.execute(_SIGNALS_TABLE)
        await db.execute(_DAILY_KPIS_TABLE)
        await db.execute(_WEIGHT_HISTORY_TABLE)
        await db.execute(_INGESTION_LOG_TABLE)
        await db.execute(_ALERTS_SENT_TABLE)

        # Create indexes
        for idx_sql in _INDEXES:
            await db.execute(idx_sql)

        await db.commit()

    logger.info(
        "Database initialized",
        db_path=db_path,
        tables=6,
        indexes=len(_INDEXES),
    )


def get_db() -> aiosqlite.Connection:
    """Get async database connection as context manager.

    Usage:
        async with get_db() as db:
            cursor = await db.execute("SELECT ...", (param,))
            rows = await cursor.fetchall()

    Returns:
        aiosqlite connection context manager.

    Raises:
        RuntimeError: If init_db() hasn't been called yet.
    """
    if _db_path is None:
        raise RuntimeError("Database not initialized. Call init_db() first.")
    return aiosqlite.connect(_db_path)


async def log_ingestion(
    *,
    system: str,
    timestamp: str,
    provider: str,
    module: str,
    status: str,
    latency_ms: int,
    data_points: int = 0,
    error: str | None = None,
    fallback_used: str | None = None,
) -> None:
    """Insert a row into ingestion_log.

    Every provider call should log through this for health monitoring.
    """
    async with get_db() as db:
        await db.execute(
            """
            INSERT INTO ingestion_log
                (system, timestamp, provider, module, status, latency_ms,
                 data_points, error, fallback_used)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                system,
                timestamp,
                provider,
                module,
                status,
                latency_ms,
                data_points,
                error,
                fallback_used,
            ),
        )
        await db.commit()


async def prune_old_data() -> dict:
    """Prune stale data based on retention policy.

    Retention:
        - ingestion_log: 30 days
        - alerts_sent: 60 days
        - signals: 90 days
        - trades, daily_kpis, weight_history: forever

    Returns:
        Dict with row counts deleted per table.
    """
    results = {}

    async with get_db() as db:
        for table, days in [
            ("ingestion_log", 30),
            ("alerts_sent", 60),
            ("signals", 90),
        ]:
            cursor = await db.execute(
                f"DELETE FROM {table} WHERE created_at < datetime('now', ?)",
                (f"-{days} days",),
            )
            results[table] = cursor.rowcount

        await db.commit()

    logger.info("Data pruning completed", pruned=results)
    return results
